export const ALL_BREEDS_REQUEST = 'ALL_BREEDS_REQUEST';
export const ALL_BREEDS_SUCCESS = 'ALL_BREEDS_SUCCESS';
export const ALL_BREEDS_FAIL = 'ALL_BREEDS_FAIL';
export const FILTER_BREEDS = 'FILTER_BREEDS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';

export const BREED_IMAGE_REQUEST = 'BREED_IMAGE_REQUEST';
export const BREED_IMAGE_SUCCESS = 'BREED_IMAGE_SUCCESS';
export const BREED_IMAGE_FAIL = 'BREED_IMAGE_FAIL';
export const BREED_SUB_BREED_REQUEST = 'BREED_SUB_BREED_REQUEST';
export const BREED_SUB_BREED_SUCCESS = 'BREED_SUB_BREED_SUCCESS';
export const CLEAR_BREED_INFO = 'CLEAR_BREED_INFO';
