export const ALL_BREEDS_REQUEST = 'ALL_BREEDS_REQUEST';
export const ALL_BREEDS_SUCCESS = 'ALL_BREEDS_SUCCESS';
export const ALL_BREEDS_FAIL = 'ALL_BREEDS_FAIL';
export const FILTER_BREEDS_REQUEST = 'FILTER_BREEDS_REQUEST';
export const CLEAR_FILTER = 'CLEAR_FILTER';
